language: python
python:
  - "3.6"
branches:
  only:
  - master
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script:
  - git fetch --all --tags
  - git fetch --unshallow
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  - git branch -a
  - ./update-gitlab-versions --dry-run
