language: python
python:
  - "3.6"
# command to install dependencies
install: pip install -r requirements.txt
# command to run tests
script:
  - pwd
  - ls -al
  - which python3
  - which python
  - ./update-gitlab-version --dry-run
